# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bb6041f2ff5333348c6325e46299cf9fe3ab40b8336eb984adfa13492f4e36f48677d9fe2027c589dbb0800fbf7e8af339a7cb54e4e295838692abcb6da700e
  app_domain: localhost:3000
  app_url: http://localhost:3000

test:
  secret_key_base: 53bd55d76caf9be5fd3f8325190f0cfff67539232b49f1aa050c75630fcc9e70ebca94926aa9b64faf5f3e736df85cd587b620765631c9b2bf4a944059ee05ae
  app_domain: localhost:3000
  app_url: http://localhost:3000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production_configs
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  app_domain: <%= ENV["APP_DOMAIN"] %>
  app_url: <%= ENV["APP_URL"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_user: <%= ENV["SMTP_USER"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>

staging:
  <<: *production_configs
